import PDFDocument from "pdfkit";
import path from "path";
import fs from "fs";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export async function generateShelfPDF(shelf, links, subject) {
  return new Promise((resolve, reject) => {
    const fileName = `shelf-${shelf._id}-${Date.now()}.pdf`;
    const filePath = path.join(__dirname, "..", "public", "pdfs", fileName);

    fs.mkdirSync(path.dirname(filePath), { recursive: true });

    const doc = new PDFDocument({ margin: 50 });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("MINDLOOM", { align: "center" });

    doc
      .fontSize(14)
      .font("Helvetica")
      .text(`Shelf: ${shelf.name}`, { align: "center" });

    if (subject) {
      doc.fontSize(12).text(`Subject: ${subject}`, { align: "center" });
    }

    doc
      .fontSize(10)
      .fillColor("#888888")
      .text(`Generated: ${new Date().toDateString()}`, { align: "center" });

    doc.moveDown(2);

    const filtered = subject
      ? links.filter((l) => l.subject === subject)
      : links;

    if (filtered.length === 0) {
      doc
        .fontSize(12)
        .fillColor("#333333")
        .text("No links found for this shelf/subject.", { align: "center" });
    }

    filtered.forEach((link, idx) => {
      doc.moveDown(0.5);

      doc
        .fontSize(12)
        .fillColor("#1A1A2E")
        .font("Helvetica-Bold")
        .text(`${idx + 1}. ${link.title || "Untitled"}`);

      doc
        .fontSize(9)
        .fillColor("#4F89C5")
        .font("Helvetica")
        .text(link.url || "", { underline: true });

      if (link.subject || link.topic) {
        doc
          .fontSize(9)
          .fillColor("#888888")
          .text(
            [link.subject, link.topic].filter(Boolean).join(" → ")
          );
      }

      if (link.summary) {
        doc
          .fontSize(10)
          .fillColor("#333333")
          .font("Helvetica")
          .text(link.summary, { indent: 10 });
      }

      if (link.vibes && link.vibes.length > 0) {
        doc
          .fontSize(9)
          .fillColor("#F4845F")
          .text(`Vibes: ${link.vibes.join(", ")}`);
      }

      doc
        .fontSize(9)
        .fillColor("#888888")
        .text(`Status: ${link.status || "fresh"}`);

      doc
        .moveTo(50, doc.y + 6)
        .lineTo(550, doc.y + 6)
        .strokeColor("#eeeeee")
        .stroke();

      doc.moveDown(0.5);
    });

    doc
      .moveDown(2)
      .fontSize(9)
      .fillColor("#aaaaaa")
      .text("Generated by MINDLOOM — Your AI knowledge companion.", {
        align: "center",
      });

    doc.end();

    stream.on("finish", () => {
      resolve({ fileName, filePath });
    });

    stream.on("error", reject);
  });
}
